services:
  postgresql:
    image: postgres:16
    container_name: press-release-db
    environment:
      POSTGRES_USER: press_release
      POSTGRES_PASSWORD: press_release
      POSTGRES_DB: press_release_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U press_release"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
