name: Deploy to EC2

on:
  push:
    branches:
      - main  # mainブランチに変更がプッシュされたら自動で動きます


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute SSH commands on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. nvm (Node.jsとnpm) を読み込むための設定
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            # EC2に入ってから実行するコマンド
            cd ~/Pr_times_hackathon/webapp/nextjs
            git pull origin main
            npm install
            npm run build
            # PM2でNext.jsを再起動（無ければ起動）
            pm2 restart nextjs-app || pm2 start npm --name "nextjs-app" -- start
